# Generated by Django 3.2.7 on 2021-09-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210911_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_checklist',
            new_name='isChecklist',
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='task.collection'),
        ),
    ]
