# Generated by Django 3.2.7 on 2021-09-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210911_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='task',
            new_name='tasks',
        ),
    ]
